### ISSUE TITLE
Keyboard pushes entire screen up and leaves space

### ISSUE THREAD

**Issue by Daphne-Android** [instachat/emoji-library#10]
This is what the chat screen looks like:
![no keyboard](https://cloud.githubusercontent.com/assets/15139703/24801920/4e3de372-1ba6-11e7-9c12-9a50cdef482d.png)

This is what it looks like as soon as the keyboard shows:
![keyboard](https://cloud.githubusercontent.com/assets/15139703/24801946/6939f31e-1ba6-11e7-9289-f945d9c6c616.png)

The emoji keyboard shows normally, but because of this weird error, the emoji keyboard and normal keyboard can be above each other.

How can I achieve what I want, which is a normal opened keyboard instead of a keyboard that pushes my entire content up with a lot of empty space showing?

I added the panel like this:
```
 <br.com.instachat.emojilibrary.model.layout.WhatsAppPanel
            android:id="@+id/bottompanel"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="false"/>
```

If I change the height to 75dp the keyboard behaves perfectly, but of course the emoji keyboard doesn't show up no more. What can I do?

**Comment by edsilfer** [comment]
When you clone the sample project, does it behaves properly or do you face the same issue? If it does works properly, please follow the same implementation. Let me know the results.

**Comment by Daphne-Android** [comment]
I tried running it several times, but it failed every time. Tried it again and now it works. When I run this demo project, I have the same issue as someone already reported: https://github.com/edsilfer/emoji-library/issues/4

**Comment by edsilfer** [comment]
Have you tried to increase the heigh of the keyboard on R.layout.rsc_emojikeyboard as suggest in https://github.com/edsilfer/emoji-library/issues/4? If you have suggestions enabled I believe that the height needs to be greater than 263dip

**Comment by Daphne-Android** [comment]
But what if someone doesn't? My application will be used on all kinds of phones with all kinds of different settings.

**Comment by edsilfer** [comment]
You can disable/enable the suggestions for the keyboard on your code if I'm not wrong. As far as I can remember there is no method to measure the height of the keyboard on a reliable way. You are more than welcome to implement a way of doing that and summiting a PR, I'll be glad to review it and merge so other people can get use of this improvement.

**Comment by Daphne-Android** [comment]
I know you can. But we can't force our clients to use a keyboard layout we want them to use. We can't let them change their entire keyboard just for one application.

Your library is great, thanks! But I think it should be... more dynamic to become really useful. Right now it feels like it's focussed on just one person using it. I'll see what I can do.

**Comment by edsilfer** [comment]
When you set the keyboard via code everything happens in a transparent way for the client, most of them not even notice that the suggestions were enabled/disabled, it won't required any action from them and it also affects only this application.

I'm sorry if the library doesn't meets you specific needs, however, I'm not making a penny out of that. In order to have something versatile we need the help of the community to maintain the project. I've done a lot, of course, based on the work of others, it would be nice to keep receiving the help of the users and improving what already exists.

**Comment by erikswed** [comment]
Actually for me adding this to the sample apps AndroidManifest -  `android:windowSoftInputMode="adjustPan"` fixes this problem. Thanks for the lib.
Update: I Notice on some devices this problem happens and on some not...

**Comment by Bakyt-Itigulov** [comment]
I have just noticed that the demo application contains 
`android:windowSoftInputMode="adjustNothing"`
for activity tag in Manifest file. After adding this tag all problems had gone.
