### ISSUE TITLE
Unable to download your library via gradle

### ISSUE THREAD

**Issue by rahul-lohra** [instachat/emoji-library#14]
Here are the links I have used in my dependencies

    compile 'br.com.instachat:emoji-library:1.0.10'
    compile 'br.com.edsilfer.android:emoji-library:1.0.10'

They both are coming unavailable

**Comment by neer17** [comment]
It would work if you use a different version `implementation 'br.com.instachat:emoji-library:1.0.8'`

**Comment by edsilfer** [comment]
I'm releasing it via Jitpack now. `README` has updated instructions
