### ISSUE TITLE
Onbackpress not working

### ISSUE THREAD

**Issue by cinohub** [instachat/emoji-library#18]
Hi,
I has implemented your EmojiCompatActivity . When keyboard does not show, my activity can back when call onBackpress(). However , when I request focus to EmojiEditext to show keyboard or show EmojiKeyboard , after that I press back button to call onBackpress(). It does work anymore. 

Here I found in your EmojiCompatActivity code :
 ```
@Override
    public void onBackPressed() {
        if (this.mOnBackPressed != null) {
            if (!this.mOnBackPressed.onBackPressed()) {
                super.onBackPressed();
            } // it lack some case to back here
        } else {
            super.onBackPressed();
        }
    }
```

**Comment by edsilfer** [comment]
Looks like `onBackPress` is returning `true` even when it is not handling the keyboard open? Did you manage to get this working? Please re-opeen if this is still an issue.
