### ISSUE TITLE
EditText not shown in when keyboard open

### ISSUE THREAD

**Issue by dhananjay23** [instachat/emoji-library#19]
Hello,

EditText not seen when a keyboard is open. I have changed in 
 `android:windowSoftInputMode=adjustPan` manifest file and remove static keyboard height.
Keyboard not update height as per different size of devices (especially Samsung device)
I have also tried to get keyboard height and set emoji_keyboard layout.

**Comment by edsilfer** [comment]
It seems that the device has a different height than the regular other ones. In that case, you need to investigate how to obtain the exact height of the soft keyboard for it. In general, the way this is done is by measuring the change in the height of the screen after the keyboard is displayed. The difference between the height is likely to be the height of the keyboard.
