### ISSUE TITLE
How to prepareKeyboard in fragment class

### ISSUE THREAD

**Issue by ghost** [instachat/emoji-library#21]
EmojiEditText userMessageInput = (EmojiEditText)v.findViewById(R.id.input_message_fragment);
        EmojiKeyboardLayout emojiKeyboardLayout=(EmojiKeyboardLayout) v.findViewById(R.id.keyboard_emoj);
        emojiKeyboardLayout.prepareKeyboard(mActivity,userMessageInput);
EmojiKeyboardLayout emojiKeyboardLayout=(EmojiKeyboardLayout) v.findViewById(R.id.keyboard_emoj);
        emojiKeyboardLayout.prepareKeyboard(mActivity,userMessageInput);

**Comment by edsilfer** [comment]
This should be no different than in a regular activity TTBOMK.
